#!/bin/sh
#
# Copyright (C) 2020-2025 SkyLabs AI.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

usage() {
	cat >&2 <<-EOF
		usage: $(basename "$0")

		This will invoke ./cpp2v-dune-gen.sh for every C or C++ file under
		the current directory, sending the dune rules to stdout.
	EOF
        exit 1
}

[ $# = 0 ] || usage

echo "; DO NOT EDIT: Generated by \"$0${1+ $*}\""

find . -name '*.[ch]' |
sort |
while read i; do
  ./cpp2v-dune-gen.sh -- $i -- -std=c99
done

find . -name '*.[ch]pp' |
sort |
while read i; do
  ./cpp2v-dune-gen.sh -s -- $i -- -std=c++23 -stdlib=libc++ -fno-builtin-std-forward
done
